#!/usr/bin/env python3
"""Generate ElevenLabs narration for the story chapters of a course.

Usage:
  ELEVENLABS_API_KEY=... python3 scripts/narrate.py --course <dir> [--voice ID] [--only mat-01-01] [--dry-run]
  ELEVENLABS_API_KEY=... python3 scripts/narrate.py --sample <voice_id> [--chars 700]

Reads every markdown material whose title starts with "Historia", cleans the
Markdown for narration, synthesizes it in paragraph-aligned chunks (with
request stitching so prosody stays continuous), concatenates the chunks
with ffmpeg into media/audio/<slug>.mp3 and turns the material into an
"audio" material that keeps the full text below the player.
Existing mp3 files are skipped, so a single chapter can be regenerated by
deleting its file.
"""
import argparse, json, os, re, subprocess, sys, tempfile, urllib.request, datetime, pathlib

API = "https://api.elevenlabs.io/v1"
MODEL = "eleven_multilingual_v2"
OUTPUT_FORMAT = "mp3_44100_64"
CHUNK_LIMIT = 4000
ROOT = pathlib.Path(__file__).resolve().parent.parent

def clean_markdown(md: str) -> str:
    out = []
    in_code = False
    for line in md.splitlines():
        s = line.rstrip()
        if s.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            out.append(s.strip())
            continue
        if re.fullmatch(r"\s*(-{3,}|\*{3,}|_{3,})\s*", s):
            out.append('<break time="1.2s" />')
            continue
        if re.match(r"^\s*\|", s):                              # tables
            if re.fullmatch(r"\s*\|?(\s*:?-{2,}:?\s*\|)+\s*", s):
                continue                                          # header separator row
            cells = [c.strip() for c in s.strip().strip("|").split("|")]
            cells = [re.sub(r"\*\*(.+?)\*\*", r"\1", c).replace("`", "") for c in cells if c]
            if cells:
                out.append(", ".join(cells) + ".")
            continue
        heading = re.match(r"^\s{0,3}#{1,6}\s+(.*)", s)
        if heading:                                               # headings: read, then a beat
            out.append(heading.group(1).strip().rstrip(".") + ".")
            out.append('<break time="0.8s" />')
            continue
        s = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", s)           # images
        s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)       # links -> text
        s = re.sub(r"^\s*[-*+]\s+", "", s)                    # bullets
        s = re.sub(r"^\s*>\s?", "", s)                        # quotes
        s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)
        s = re.sub(r"(?<!\w)\*(.+?)\*(?!\w)", r"\1", s)
        s = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"\1", s)
        s = s.replace("`", "")
        out.append(s)
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text

def chunk(text: str, limit=CHUNK_LIMIT):
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks, cur = [], ""
    for p in paras:
        cand = (cur + "\n\n" + p) if cur else p
        if len(cand) > limit and cur:
            chunks.append(cur); cur = p
        else:
            cur = cand
    if cur: chunks.append(cur)
    return chunks

def tts(key, voice, text, prev_ids, prev_text, next_text):
    body = {
        "text": text, "model_id": MODEL,
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75, "style": 0.0, "use_speaker_boost": True},
    }
    if prev_ids: body["previous_request_ids"] = prev_ids[-3:]
    if prev_text: body["previous_text"] = prev_text[-500:]
    if next_text: body["next_text"] = next_text[:500]
    req = urllib.request.Request(
        f"{API}/text-to-speech/{voice}?output_format={OUTPUT_FORMAT}",
        data=json.dumps(body).encode(), method="POST",
        headers={"xi-api-key": key, "Content-Type": "application/json", "Accept": "audio/mpeg"})
    with urllib.request.urlopen(req, timeout=600) as r:
        return r.read(), r.headers.get("request-id")

def synthesize(key, voice, text, out_path: pathlib.Path):
    chunks = chunk(text)
    tmpdir = tempfile.mkdtemp()
    parts, ids = [], []
    for i, c in enumerate(chunks):
        prev_text = chunks[i-1] if i else None
        next_text = chunks[i+1] if i+1 < len(chunks) else None
        audio, rid = tts(key, voice, c, ids, prev_text, next_text)
        p = pathlib.Path(tmpdir) / f"part{i:03d}.mp3"
        p.write_bytes(audio); parts.append(p)
        if rid: ids.append(rid)
        print(f"    chunk {i+1}/{len(chunks)} ({len(c)} chars) ok", flush=True)
    lst = pathlib.Path(tmpdir) / "list.txt"
    lst.write_text("".join(f"file '{p}'\n" for p in parts))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy", str(out_path)], check=True)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--course"); ap.add_argument("--voice")
    ap.add_argument("--only"); ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--sample"); ap.add_argument("--chars", type=int, default=700)
    ap.add_argument("--prefix", default=None, help="mp3 filename prefix (default: course dir name)")
    ap.add_argument("--titles", default="Historia", help="narrate materials whose title starts with this (default: Historia)")
    a = ap.parse_args()
    key = os.environ.get("ELEVENLABS_API_KEY")
    if not key and not a.dry_run: sys.exit("ELEVENLABS_API_KEY not set")

    if a.sample:
        course = ROOT / "courses" / (a.course or "ingeniero-de-software-en-la-era-de-la-ia")
        md = (course / "materials/01-01-historia-el-riego-fantasma.md").read_text()
        text = clean_markdown(md)[:a.chars]
        text = text[:text.rfind(".")+1]
        out = ROOT / "scratch-samples" / f"sample-{a.sample}.mp3"
        out.parent.mkdir(exist_ok=True)
        synthesize(key, a.sample, text, out); print(out); return

    course = ROOT / "courses" / a.course
    cj = course / "course.json"
    data = json.loads(cj.read_text())
    prefix = a.prefix or a.course
    total = 0; changed = False
    for s in data["sections"]:
        for m in s["materials"]:
            if not m["title"].startswith(a.titles) or not m.get("markdownFile"): continue
            if a.only and m["id"] != a.only: continue
            text = clean_markdown((course / m["markdownFile"]).read_text())
            stem = pathlib.Path(m["markdownFile"]).stem
            slug = re.sub(r"^\d+-\d+-historia-", "", stem)
            num = m["id"].split("-")[1]
            rel = f"media/audio/{prefix}-{num}-{slug}.mp3" if slug != stem else f"media/audio/{prefix}-{stem}.mp3"
            out = ROOT / rel
            total += len(text)
            print(f"{m['id']}  {len(text):6d} chars  {len(chunk(text))} chunks -> {rel}")
            if a.dry_run: continue
            if not out.exists():
                synthesize(key, a.voice, text, out)
            if m["type"] != "audio" or m.get("mediaPath") != rel:
                m["type"] = "audio"; m["mediaPath"] = rel; changed = True
    print(f"TOTAL {total} chars")
    if changed and not a.dry_run:
        data["updatedAt"] = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        cj.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print("course.json updated")

if __name__ == "__main__":
    main()
